[dev]
command = "vite dev"

[build]
command = "vite build"
functions = "functions"
publish = "public"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
